### ISSUE TITLE
Implement Mozilla specific claims extraction

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#55]
Currently we have only one piece of code that builds the list of principals from the JWT payload, which could serve as the generic one.

According to @gdestuynder, we should read the user info (email, groups, etc.) from a field called `https://sso.mozilla.com/claims/cis` in the JWT payload.

Since this is specific to the Auth0 setup at Mozilla, we could have a setting in the policies files to specify the type of «extractor» to use

**Comment by gdestuynder** [comment]
the claim should be read from the user info endpoint, not the JWT (`id_token`).
it may be present in the JWT, but it's not recommended to read it from there because the JWT has a size limit thus it does not necessarily always contains all the data - and in practice we have cases where it will not. OIDC libraries generally give you both the JWT and the user info endpoint data back by default.

The claim names are specific, but the user info endpoint itself is OIDC standard - OIDC also mention that past the basic fields, extra claims are custom unique names (http://openid.net/specs/openid-connect-implicit-1_0.html#StandardClaims).

**Comment by leplatrem** [comment]
Thanks for these precisions!
Also, I now remember that this cis field is only present with the `profile` scope...

We'll investigate if it makes sense for us to fetch the proflle info (adding an extra request cost)

**Comment by gdestuynder** [comment]
For complete understanding: 

while group data is currently available in the `id_token` it will not be available there forever. We're currently running in "historical" compatibility mode, but passing extra claims (like `groups`) to the `id_token` is not recommended by the OIDC spec group and our access provider (auth0) will eventually remove that possibility entierely.

While I do not like this (it breaks compat for us, for older RPs, so we've to work with the one that makes use of the `groups` claim directly from the `id_token`, which is thanksfully a relatively rare case), they're technically right - passing large amount of data over the `id_token` will always eventually break due to size constraints. An additional HTTP request is a small cost for this, and is already part of the spec to begin with, thus I would highly recommend making the request.

Alternatives: utilizing SAML or WS-Federation instead (it's usually more painful to implement though, and not necessarily much faster)

**Comment by leplatrem** [comment]
Changes in Mozilla+Auth0 will happen:

> [...]
> This means, if you were using the `groups` claim in particular, you will now have to use the namespaced claim called `https://sso.mozilla.com/claims/groups` which contains the same data.
> 
> If you need to query more information about the user, you will need to query the CIS PersonAPI (https://github.com/mozilla-iam/person-api ) which has no such limitations. Please contact us for help utilizing this endpoint.

**Comment by leplatrem** [comment]
I'll mark this issue as resolved by #72 and tackle the userinfo part in #80
