### ISSUE TITLE
Gather all configuration values into one struct

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#63]
Have one config struct that contains every env values (initialized at startup) and pass it around instead of having scattered `os.Getenv()`.

**Comment by mostlygeek** [comment]
Here's [how I do it in go-syncstorage](https://github.com/mozilla-services/go-syncstorage/blob/master/config/config.go). 

In the package's `init()` function I set a bunch of package level variables so I can access the config with `config.SomeVariable` because I like the ergonomics of it. 

I only [use the config.* globals](https://github.com/mozilla-services/go-syncstorage/blob/master/server.go#L40-L46) in the `main` package.  

My web handlers have their own configuration structs.  I fill those out in `main()` ([example](https://github.com/mozilla-services/go-syncstorage/blob/master/server.go#L48-L57), [example](https://github.com/mozilla-services/go-syncstorage/blob/master/server.go#L62-L64)). I find this keeps packages and `main()` decoupled and easier to refactor things.
